spring.application.name=studbuds

server.tomcat.accesslog.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:postgresql://dpg-d6nl71fgi27c73a6dsog-a.oregon-postgres.render.com/user_database_zci9
spring.datasource.username=user_database_zci9_user
spring.datasource.password=WvDJnYR53xQ8TjCG67xSwQU9Ev4JMiYQ